# Generated by Django 5.2.3 on 2025-06-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='chef_profiles/'),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
