# Generated by Django 5.2.3 on 2025-06-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_phone_number_alter_chefprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='chefprofile',
            name='bank_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
