# Generated by Django 5.2.3 on 2025-06-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
