# Generated by Django 5.2.3 on 2025-06-14 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_dish_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='delivery_slot',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_paused',
        ),
        migrations.AddField(
            model_name='subscription',
            name='meals_per_week',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic Plan'), ('premium', 'Premium Plan'), ('vip', 'VIP Plan')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_per_meal',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
